server:
  port: 8091

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      teste: teste
    consumer:
      group-id: payment-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/payment-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: off