server:
  port: 8092

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      inventory-success: inventory-validation-success
      inventory-fail: inventory-validation-fail
      orchestrator: orchestrator
    consumer:
      group-id: inventory-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/inventory-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: off